include: package:effective_dart/analysis_options.yaml
# include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true

# List of available lint rules: https://dart-lang.github.io/linter/lints/
# For more information about
# customizing analysis: https://dart.dev/guides/language/analysis-options#enabling-linter-rules
linter:
  rules:
  # Error Rules
    - avoid_empty_else # Pedantic, Flutter
    - cancel_subscriptions # Flutter
    - close_sinks # Flutter
    - control_flow_in_finally # Flutter
    - avoid_types_as_parameter_names # Pedantic
    - no_duplicate_case_values # Pedantic
    # - test_types_in_equals # Flutter
    - throw_in_finally # Flutter
    - unnecessary_statements # Flutter
    - unrelated_type_equality_checks # Pedantic, Flutter
    - valid_regexps # Pedantic, Flutter
  # Style Rules
    - always_declare_return_types # Pedantic
    - always_put_required_named_parameters_first
    - always_require_non_null_named_parameters # Pedantic
    - annotate_overrides # Pedantic
    - avoid_shadowing_type_parameters # Pedantic
    - await_only_futures # Flutter
    - empty_catches # Pedantic
    - flutter_style_todos
    - null_closures # Pedantic
    - prefer_conditional_assignment # Pedantic
    - prefer_contains # Pedantic
    - prefer_expression_function_bodies
    - prefer_for_elements_to_map_fromIterable # Pedantic
    - prefer_if_null_operators # Pedantic
    - prefer_is_empty # Pedantic
    - prefer_is_not_empty # Pedantic, Flutter
    - prefer_single_quotes # Pedantic
    - prefer_spread_collections # Pedantic
    - recursive_getters # Pedantic
    - sized_box_for_whitespace
    - sort_constructors_first
    - sort_child_properties_last
    - unawaited_futures # Pedantic
    - unnecessary_await_in_return
    - unnecessary_final
    - unnecessary_parenthesis
